server:
  port: 38060
  error:
    path: /error
  servlet:
    context-path: /ddns-namesilo
    session:
      tracking-modes: cookie
      timeout: 3H
      cookie:
        http-only: true
    application-display-name: ddns-namesilo
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: ddns-namesilo-测试环境
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      suffix: .jsp
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      deserialization:
        accept_empty_string_as_null_object: true
  devtools:
    restart:
      enabled: true
  messages:
    basename: i18n/message
    encoding: utf-8
  freemarker:
    #req访问request
    request-context-attribute: req
    #后缀名
    suffix: .ftl
    content-type: text/html; charset=UTF-8
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:templates/, file:./templates/
    charset: UTF-8 #编码格式
    expose-spring-macro-helpers: true
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
      auto_import: spring.ftl as spring
      default_encoding: UTF-8
      output_encoding: UTF-8

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

chqiuu:
  ddns:
    local-resource-path:
    swagger-enable: true
    exclude-local-ips:
      - 127.0.0.1
      - localhost
      - 118.112.188.82
    domains:
      - type: A
        domain: 222.chqiuu.com
      - type: AAAA
        domain: 111.chqiuu.com
    namesilo-api-key: 222